/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#334155',
        'outline': '#737686',
        'outline-variant': '#cbd5e1',
        'primary': '#0f172a',
        'primary-container': '#172554',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'brand': {
          50: '#eff6ff',
          100: '#dbeafe',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        },
        'canvas': {
          950: '#070d1e',
          900: '#0b1329',
          850: '#0f172a',
          800: '#151e36',
          700: '#1e2942',
          600: '#2c3b59',
        },
      },
      fontFamily: {
        sans: ['Inter', 'Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        display: ['Hanken Grotesk', 'Inter', 'sans-serif'],
        headline: ['Hanken Grotesk', 'Inter', 'sans-serif'],
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
      },
    },
  },
  plugins: [],
};
